# Generated by Django 4.2.1 on 2023-05-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_rename_pagina_livros_paginas_alter_livros_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='imagem',
            field=models.ImageField(default='', upload_to='uploads/'),
        ),
    ]
